name: noPhantomsPlugin
version: 1.0
author: 3urobeat
main: org.x3urobeat.noPhantomsPlugin.Main
description: Prevents Phantoms from spawning.

commands:
  nophantomsinfo:
    description: What's this? (Help)
